#!/bin/bash

export DISCORD_TOKEN="$(cat CRED_TOKEN)"
export DISCORD_CLIENT_ID="$(cat CRED_CLIENTID)"
export DISCORD_DEV_SERVER="$(cat CRED_DEVSERVER)"
export SLACK_TOKEN="$(cat CRED_SLACK_TOKEN)"
export SLACK_APPTOKEN="$(cat CRED_SLACKAPP)"
export COOKIE_VALUE="$(cat CRED_ESPN)"
export PG_CONNECTION="$(cat CRED_PG)"
export CRYPTO_ALGORITHM="$(cat CRED_ALG)"
export CRYPTO_KEY="$(cat CRED_CRYPTKEY)"
